"""CDS v2 — scientific computing on the NumPy/SciPy/pandas/matplotlib stack.

The successor to the zero-dependency cognitive-discovery-system (v1.x),
rebuilding its proven algorithms for speed and adding new domain modules.
"""

from __future__ import annotations

from . import (
    cli,
    graph,
    integrate,
    interpolate,
    io,
    linalg,
    ml,
    montecarlo,
    optimize,
    signals,
    stats,
    timeseries,
    viz,
)
from ._version import __version__
from .graph import (
    ComponentResult,
    DegreeResult,
    ShortestPaths,
    bellman_ford_paths,
    connected_components,
    degree,
    floyd_warshall_paths,
    from_edges,
    minimum_spanning_forest,
    pagerank,
    shortest_paths,
    single_source_shortest_paths,
    topological_order,
)
from .integrate import (
    OdeResult,
    QuadResult,
    cumulative_trapezoid,
    integrate_2d,
    integrate_3d,
    quad,
    simpson,
    solve_ivp,
    trapezoid,
)
from .interpolate import (
    cubic_spline,
    grid_interp,
    lagrange_poly,
    linear_interp,
    pchip_interpolator,
    regular_grid_interp,
)
from .linalg import (
    EigenResult,
    LeastSquaresResult,
    SVDResult,
    cholesky,
    cond,
    det,
    eig,
    eigh,
    inv,
    lstsq,
    matrix_power,
    norm,
    pinv,
    rank,
    solve,
    svd,
    trace,
)
from .montecarlo import hit_or_miss, mc_expectation, mc_integrate, pi_estimate
from .optimize import (
    FitResult,
    LinprogResult,
    OptimizationResult,
    curve_fit,
    find_root_scalar,
    least_squares,
    linprog,
    minimize,
    minimize_scalar,
    newton_root,
    root,
)
from .signals import (
    PeakResult,
    SpectrogramResult,
    Spectrum,
    butter_bandpass,
    butter_highpass,
    butter_lowpass,
    convolve_signals,
    correlate_signals,
    envelope,
    fft,
    fftfreq,
    filter_signal,
    find_peaks,
    ifft,
    irfft,
    power_spectrum,
    resample_signal,
    rfft,
    spectrogram,
    welch_spectrum,
)
from .signals import (
    moving_average as moving_average_signal,
)
from .stats import (
    CorrelationResult,
    DescribeResult,
    TestResult,
    anova,
    chi_square_independence,
    cohens_d,
    cramers_v,
    describe,
    eta_squared_from_f,
    independent_t_test,
    kendall_tau,
    kruskal_wallis,
    levene_test,
    mann_whitney_u,
    norm_cdf,
    norm_pdf,
    norm_ppf,
    normality_test,
    paired_t_test,
    pearson_correlation,
    percentile,
    spearman_correlation,
    t_test,
    wilcoxon_signed_rank,
    z_scores,
)
from .timeseries import (
    DecompositionResult,
    acf,
    difference,
    exponential_smoothing,
    ljung_box,
    moving_average,
    pacf,
    seasonal_decompose,
)

__all__ = [
    "__version__",
    "cli",
    "graph",
    "integrate",
    "interpolate",
    "io",
    "linalg",
    "ml",
    "montecarlo",
    "optimize",
    "signals",
    "stats",
    "timeseries",
    "viz",
    # graph
    "ComponentResult",
    "DegreeResult",
    "ShortestPaths",
    "bellman_ford_paths",
    "connected_components",
    "degree",
    "floyd_warshall_paths",
    "from_edges",
    "minimum_spanning_forest",
    "pagerank",
    "shortest_paths",
    "single_source_shortest_paths",
    "topological_order",
    # integrate
    "OdeResult",
    "QuadResult",
    "cumulative_trapezoid",
    "integrate_2d",
    "integrate_3d",
    "quad",
    "simpson",
    "solve_ivp",
    "trapezoid",
    # interpolate
    "cubic_spline",
    "grid_interp",
    "lagrange_poly",
    "linear_interp",
    "pchip_interpolator",
    "regular_grid_interp",
    # linalg
    "EigenResult",
    "LeastSquaresResult",
    "SVDResult",
    "cholesky",
    "cond",
    "det",
    "eig",
    "eigh",
    "inv",
    "lstsq",
    "matrix_power",
    "norm",
    "pinv",
    "rank",
    "solve",
    "svd",
    "trace",
    # montecarlo
    "hit_or_miss",
    "mc_expectation",
    "mc_integrate",
    "pi_estimate",
    # optimize
    "FitResult",
    "LinprogResult",
    "OptimizationResult",
    "curve_fit",
    "find_root_scalar",
    "least_squares",
    "linprog",
    "minimize",
    "minimize_scalar",
    "newton_root",
    "root",
    # signals
    "PeakResult",
    "SpectrogramResult",
    "Spectrum",
    "butter_bandpass",
    "butter_highpass",
    "butter_lowpass",
    "convolve_signals",
    "correlate_signals",
    "envelope",
    "fft",
    "fftfreq",
    "filter_signal",
    "find_peaks",
    "ifft",
    "irfft",
    "moving_average_signal",
    "power_spectrum",
    "resample_signal",
    "rfft",
    "spectrogram",
    "welch_spectrum",
    # stats
    "CorrelationResult",
    "DescribeResult",
    "TestResult",
    "anova",
    "chi_square_independence",
    "cohens_d",
    "cramers_v",
    "describe",
    "eta_squared_from_f",
    "independent_t_test",
    "kendall_tau",
    "kruskal_wallis",
    "levene_test",
    "mann_whitney_u",
    "norm_cdf",
    "norm_pdf",
    "norm_ppf",
    "normality_test",
    "paired_t_test",
    "pearson_correlation",
    "percentile",
    "spearman_correlation",
    "t_test",
    "wilcoxon_signed_rank",
    "z_scores",
    # timeseries
    "DecompositionResult",
    "acf",
    "difference",
    "exponential_smoothing",
    "ljung_box",
    "moving_average",
    "pacf",
    "seasonal_decompose",
]
